spring.datasource.url=jdbc:postgresql://ep-mute-hill-az64ef3a-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_S5OtwEWkx4qP

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8080

spring.mvc.pathmatch.matching-strategy=ant_path_matcher